<Project>
  <PropertyGroup>
    <ProjectName>DrinksAndDrugs</ProjectName>
    <BaseGamePath>C:\Program Files (x86)\Steam\steamapps\common\Casualties Unknown Demo</BaseGamePath>
    <BepInExDir>$(BaseGamePath)/BepInEx</BepInExDir>
    <GameAssembliesDir>$(BaseGamePath)/CasualtiesUnknown_Data/Managed</GameAssembliesDir>
  </PropertyGroup>
</Project>
